package Design;

import DAO.CrudAkun;
import Pesantren.Akun;
import Validasi.ValidasiInputan;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FormLupaPassword extends javax.swing.JFrame {

    ValidasiInputan vld = new ValidasiInputan();
    Akun akun = new Akun();
    CrudAkun log = new CrudAkun();

    public FormLupaPassword() {
        initComponents();

        teksPassTerakhir.setEchoChar((char) 0);
        ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\Bahasa Fundamental\\ProjekJava - Ahmad Faisal Hidayat\\src\\gambar\\hidden.png");
        buttonMata2.setIcon(icon);
        jLabel7.setVisible(false);
        teksPassTerbaru.setVisible(false);
        buttonMata1.setVisible(false);
        jSeparator4.setVisible(false);
        buttonGanti.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        teksUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        teksPassTerbaru = new javax.swing.JPasswordField();
        buttonMata1 = new javax.swing.JLabel();
        buttonCari = new javax.swing.JLabel();
        buttonGanti = new javax.swing.JButton();
        ValidasiTeksPass = new javax.swing.JLabel();
        teksPassTerakhir = new javax.swing.JPasswordField();
        buttonMata2 = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JLabel();
        buttonMinimize = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 375));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jPanel6.setBackground(new java.awt.Color(0, 155, 76));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/images (1).png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 69, -1, -1));

        teksUser.setBackground(new java.awt.Color(250, 250, 250));
        teksUser.setForeground(new java.awt.Color(0, 0, 0));
        teksUser.setText("Username");
        teksUser.setBorder(null);
        teksUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksUserFocusLost(evt);
            }
        });
        jPanel7.add(teksUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 69, 200, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 91, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/padlock.png"))); // NOI18N
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 141, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 168, 200, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/padlock.png"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, -1));

        teksPassTerbaru.setBackground(new java.awt.Color(250, 250, 250));
        teksPassTerbaru.setForeground(new java.awt.Color(0, 0, 0));
        teksPassTerbaru.setText("Masukan Password Terbaru");
        teksPassTerbaru.setBorder(null);
        teksPassTerbaru.setEchoChar('*');
        teksPassTerbaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksPassTerbaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksPassTerbaruFocusLost(evt);
            }
        });
        teksPassTerbaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksPassTerbaruKeyReleased(evt);
            }
        });
        jPanel7.add(teksPassTerbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, -1));

        buttonMata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/eye.png"))); // NOI18N
        buttonMata1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMata1MouseClicked(evt);
            }
        });
        jPanel7.add(buttonMata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 16));

        buttonCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(0, 0, 0));
        buttonCari.setText("cari");
        buttonCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCariMouseClicked(evt);
            }
        });
        jPanel7.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 146, -1, -1));

        buttonGanti.setBackground(new java.awt.Color(0, 155, 76));
        buttonGanti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonGanti.setForeground(new java.awt.Color(255, 255, 255));
        buttonGanti.setText("GANTI");
        buttonGanti.setMaximumSize(new java.awt.Dimension(84, 26));
        buttonGanti.setMinimumSize(new java.awt.Dimension(84, 26));
        buttonGanti.setPreferredSize(new java.awt.Dimension(84, 26));
        buttonGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGantiActionPerformed(evt);
            }
        });
        jPanel7.add(buttonGanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 30));

        ValidasiTeksPass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(ValidasiTeksPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 248, -1, -1));

        teksPassTerakhir.setBackground(new java.awt.Color(250, 250, 250));
        teksPassTerakhir.setForeground(new java.awt.Color(0, 0, 0));
        teksPassTerakhir.setText("Password Terakhir");
        teksPassTerakhir.setBorder(null);
        teksPassTerakhir.setEchoChar('*');
        teksPassTerakhir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksPassTerakhirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksPassTerakhirFocusLost(evt);
            }
        });
        jPanel7.add(teksPassTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 146, 170, -1));

        buttonMata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/eye.png"))); // NOI18N
        buttonMata2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMata2MouseClicked(evt);
            }
        });
        jPanel7.add(buttonMata2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 146, -1, 16));

        buttonKembali.setForeground(new java.awt.Color(0, 0, 0));
        buttonKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back (1).png"))); // NOI18N
        buttonKembali.setText("KEMBALI");
        buttonKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKembaliMouseClicked(evt);
            }
        });
        jPanel7.add(buttonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        buttonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/minimize (1).png"))); // NOI18N
        buttonMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizeMouseClicked(evt);
            }
        });
        jPanel7.add(buttonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teksUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksUserFocusLost
        if (teksUser.getText().equals("")) {
            teksUser.setText("Username");
        }
    }//GEN-LAST:event_teksUserFocusLost

    private void teksUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksUserFocusGained
        if (teksUser.getText().equals("Username")) {
            teksUser.setText("");
        }
    }//GEN-LAST:event_teksUserFocusGained

    private void teksPassTerbaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksPassTerbaruFocusGained
        if (teksPassTerbaru.getText().equals("Masukan Password Terbaru")) {
            teksPassTerbaru.setText("");
        }
    }//GEN-LAST:event_teksPassTerbaruFocusGained

    private void teksPassTerbaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksPassTerbaruFocusLost
        if (teksPassTerbaru.getText().equals("")) {
            teksPassTerbaru.setText("Masukan Password Terbaru");
        }
    }//GEN-LAST:event_teksPassTerbaruFocusLost

    private void teksPassTerbaruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksPassTerbaruKeyReleased
        if (teksPassTerbaru.getText().length() < 6) {
            ValidasiTeksPass.setText("Minimal 6 Karakter");
        } else if (teksPassTerbaru.getText().length() > 25) {
            ValidasiTeksPass.setText("Maksimal 25 Karakter");
        } else {
            ValidasiTeksPass.setText("");
        }

        if (vld.cekPassword(teksPassTerbaru.getText()) != 0) {
            ValidasiTeksPass.setText("Masukan Data Dengan Benar");
        }
    }//GEN-LAST:event_teksPassTerbaruKeyReleased
    boolean cek = true;
    private void buttonMata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMata1MouseClicked
        if (cek) {
            teksPassTerbaru.setEchoChar((char) 0);
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/hidden.png");
            buttonMata1.setIcon(icon);
            cek = false;
        } else {
            teksPassTerbaru.setEchoChar('\u002a');
            ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\Bahasa Fundamental\\JAVA\\ProjekJava - Ahmad Faisal Hidayat\\src\\gambar\\eye.png");
            buttonMata1.setIcon(icon);
            cek = true;
        }
    }//GEN-LAST:event_buttonMata1MouseClicked

    private void buttonCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCariMouseClicked
        if (teksUser.getText().equals("Username") || teksPassTerakhir.getText().equals("Password Terakhir")) {
            JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar", "", JOptionPane.WARNING_MESSAGE);
        } else {
            akun.setUsername(teksUser.getText());
            akun.setPassword(teksPassTerakhir.getText());

            if (log.lupaPassword(akun) == 1) {
                jLabel7.setVisible(true);
                teksPassTerbaru.setVisible(true);
                teksPassTerbaru.setEchoChar((char) 0);
                ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\Bahasa Fundamental\\ProjekJava - Ahmad Faisal Hidayat\\src\\gambar\\hidden.png");
                buttonMata1.setIcon(icon);
                buttonMata1.setVisible(true);
                jSeparator4.setVisible(true);
                buttonGanti.setVisible(true);
            }
        }
    }//GEN-LAST:event_buttonCariMouseClicked

    private void teksPassTerakhirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksPassTerakhirFocusGained
        if (teksPassTerakhir.getText().equals("Password Terakhir")) {
            teksPassTerakhir.setText("");
        }
    }//GEN-LAST:event_teksPassTerakhirFocusGained

    private void teksPassTerakhirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksPassTerakhirFocusLost
        if (teksPassTerakhir.getText().equals("")) {
            teksPassTerakhir.setText("Password Terakhir");
        }
    }//GEN-LAST:event_teksPassTerakhirFocusLost
    boolean cek2 = true;
    private void buttonMata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMata2MouseClicked
        if (cek) {
            teksPassTerakhir.setEchoChar((char) 0);
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/hidden.png");
            buttonMata2.setIcon(icon);
            cek = false;
        } else {
            teksPassTerakhir.setEchoChar('\u002a');
            ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\Bahasa Fundamental\\JAVA\\ProjekJava - Ahmad Faisal Hidayat\\src\\gambar\\eye.png");
            buttonMata2.setIcon(icon);
            cek = true;
        }
    }//GEN-LAST:event_buttonMata2MouseClicked

    private void buttonGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGantiActionPerformed
        if (teksPassTerbaru.getText().equals("Masukan Password Terbaru")) {
            JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar", "", JOptionPane.WARNING_MESSAGE);
        } else {
            akun.setPassword(teksPassTerbaru.getText());

            if (log.updatePassword(akun) == 1) {
                JOptionPane.showMessageDialog(this, "Password Berhasil Diganti", "", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                FormLogin login = new FormLogin();
                login.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Password Gagal Diganti", "", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonGantiActionPerformed

    private void buttonKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKembaliMouseClicked
        this.dispose();
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_buttonKembaliMouseClicked

    private void buttonMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_buttonMinimizeMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int jawab = JOptionPane.showOptionDialog(this,
            "Anda Ingin Keluar",
            "KELUAR",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLupaPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ValidasiTeksPass;
    private javax.swing.JLabel buttonCari;
    private javax.swing.JButton buttonGanti;
    private javax.swing.JLabel buttonKembali;
    private javax.swing.JLabel buttonMata1;
    private javax.swing.JLabel buttonMata2;
    private javax.swing.JLabel buttonMinimize;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField teksPassTerakhir;
    private javax.swing.JPasswordField teksPassTerbaru;
    private javax.swing.JTextField teksUser;
    // End of variables declaration//GEN-END:variables
}
