package Design;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FormMenu extends javax.swing.JFrame {

    public FormMenu() {
        initComponents();
        
        teksJudul.setText("Dashboard");
        
        PanelDashboard pds = new PanelDashboard();
        PanelWarnaDashboard1.setBackground(Color.BLACK);
        PanelWarnaDashboard2.setBackground(Color.BLACK);
        PanelWarnaSantri1.setBackground(Color.GRAY);
        PanelWarnaSantri2.setBackground(Color.GRAY);
        PanelWarnaWaliSantri1.setBackground(Color.GRAY);
        PanelWarnaWaliSantri2.setBackground(Color.GRAY);
        PanelWarnaPengajar1.setBackground(Color.GRAY);
        PanelWarnaPengajar2.setBackground(Color.GRAY);
        PanelWarnaKamar1.setBackground(Color.GRAY);
        PanelWarnaKamar2.setBackground(Color.GRAY);
        PanelMenu.removeAll();
        PanelMenu.repaint();
        PanelMenu.revalidate();
        PanelMenu.add(pds);
        PanelMenu.repaint();
        PanelMenu.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelDataSantri = new javax.swing.JPanel();
        PanelWarnaSantri1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelWarnaSantri2 = new javax.swing.JPanel();
        PanelDashboard = new javax.swing.JPanel();
        PanelWarnaDashboard1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelWarnaDashboard2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        PanelDataWaliSantri = new javax.swing.JPanel();
        PanelWarnaWaliSantri1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanelWarnaWaliSantri2 = new javax.swing.JPanel();
        PanelDataPengajar = new javax.swing.JPanel();
        PanelWarnaPengajar1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelWarnaPengajar2 = new javax.swing.JPanel();
        PanelDataAkun = new javax.swing.JPanel();
        PanelWarnaKamar1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PanelWarnaKamar2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        teksJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        PanelMenu = new javax.swing.JPanel();
        buttonMinimize = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/LOGO-ASSHOFA-1024x237 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        PanelDataSantri.setBackground(new java.awt.Color(255, 255, 255));
        PanelDataSantri.setForeground(new java.awt.Color(0, 0, 0));
        PanelDataSantri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDataSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDataSantriMouseClicked(evt);
            }
        });

        PanelWarnaSantri1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaSantri1Layout = new javax.swing.GroupLayout(PanelWarnaSantri1);
        PanelWarnaSantri1.setLayout(PanelWarnaSantri1Layout);
        PanelWarnaSantri1Layout.setHorizontalGroup(
            PanelWarnaSantri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaSantri1Layout.setVerticalGroup(
            PanelWarnaSantri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Data Santri");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/santri (1).png"))); // NOI18N

        PanelWarnaSantri2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaSantri2Layout = new javax.swing.GroupLayout(PanelWarnaSantri2);
        PanelWarnaSantri2.setLayout(PanelWarnaSantri2Layout);
        PanelWarnaSantri2Layout.setHorizontalGroup(
            PanelWarnaSantri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaSantri2Layout.setVerticalGroup(
            PanelWarnaSantri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDataSantriLayout = new javax.swing.GroupLayout(PanelDataSantri);
        PanelDataSantri.setLayout(PanelDataSantriLayout);
        PanelDataSantriLayout.setHorizontalGroup(
            PanelDataSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataSantriLayout.createSequentialGroup()
                .addComponent(PanelWarnaSantri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(105, 105, 105)
                .addComponent(PanelWarnaSantri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelDataSantriLayout.setVerticalGroup(
            PanelDataSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelWarnaSantri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PanelDataSantriLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
            .addComponent(PanelWarnaSantri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(PanelDataSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 313, -1, -1));

        PanelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        PanelDashboard.setForeground(new java.awt.Color(0, 0, 0));
        PanelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDashboard.setPreferredSize(new java.awt.Dimension(370, 60));
        PanelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDashboardMouseClicked(evt);
            }
        });
        PanelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelWarnaDashboard1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaDashboard1Layout = new javax.swing.GroupLayout(PanelWarnaDashboard1);
        PanelWarnaDashboard1.setLayout(PanelWarnaDashboard1Layout);
        PanelWarnaDashboard1Layout.setHorizontalGroup(
            PanelWarnaDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaDashboard1Layout.setVerticalGroup(
            PanelWarnaDashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelDashboard.add(PanelWarnaDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dashboard");
        PanelDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/DashBoard (1).png"))); // NOI18N
        PanelDashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 0, -1, 60));

        PanelWarnaDashboard2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaDashboard2Layout = new javax.swing.GroupLayout(PanelWarnaDashboard2);
        PanelWarnaDashboard2.setLayout(PanelWarnaDashboard2Layout);
        PanelWarnaDashboard2Layout.setHorizontalGroup(
            PanelWarnaDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaDashboard2Layout.setVerticalGroup(
            PanelWarnaDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelDashboard.add(PanelWarnaDashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 0, -1, 60));

        jPanel1.add(PanelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 213, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 370, -1));

        PanelDataWaliSantri.setBackground(new java.awt.Color(255, 255, 255));
        PanelDataWaliSantri.setForeground(new java.awt.Color(0, 0, 0));
        PanelDataWaliSantri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDataWaliSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDataWaliSantriMouseClicked(evt);
            }
        });

        PanelWarnaWaliSantri1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaWaliSantri1Layout = new javax.swing.GroupLayout(PanelWarnaWaliSantri1);
        PanelWarnaWaliSantri1.setLayout(PanelWarnaWaliSantri1Layout);
        PanelWarnaWaliSantri1Layout.setHorizontalGroup(
            PanelWarnaWaliSantri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaWaliSantri1Layout.setVerticalGroup(
            PanelWarnaWaliSantri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data Wali Santri");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/family (1).png"))); // NOI18N

        PanelWarnaWaliSantri2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaWaliSantri2Layout = new javax.swing.GroupLayout(PanelWarnaWaliSantri2);
        PanelWarnaWaliSantri2.setLayout(PanelWarnaWaliSantri2Layout);
        PanelWarnaWaliSantri2Layout.setHorizontalGroup(
            PanelWarnaWaliSantri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        PanelWarnaWaliSantri2Layout.setVerticalGroup(
            PanelWarnaWaliSantri2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDataWaliSantriLayout = new javax.swing.GroupLayout(PanelDataWaliSantri);
        PanelDataWaliSantri.setLayout(PanelDataWaliSantriLayout);
        PanelDataWaliSantriLayout.setHorizontalGroup(
            PanelDataWaliSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataWaliSantriLayout.createSequentialGroup()
                .addComponent(PanelWarnaWaliSantri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(PanelWarnaWaliSantri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelDataWaliSantriLayout.setVerticalGroup(
            PanelDataWaliSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelWarnaWaliSantri1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDataWaliSantriLayout.createSequentialGroup()
                .addGroup(PanelDataWaliSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelWarnaWaliSantri2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDataWaliSantriLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(PanelDataWaliSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 413, 370, 60));

        PanelDataPengajar.setBackground(new java.awt.Color(255, 255, 255));
        PanelDataPengajar.setForeground(new java.awt.Color(0, 0, 0));
        PanelDataPengajar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDataPengajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDataPengajarMouseClicked(evt);
            }
        });

        PanelWarnaPengajar1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaPengajar1Layout = new javax.swing.GroupLayout(PanelWarnaPengajar1);
        PanelWarnaPengajar1.setLayout(PanelWarnaPengajar1Layout);
        PanelWarnaPengajar1Layout.setHorizontalGroup(
            PanelWarnaPengajar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaPengajar1Layout.setVerticalGroup(
            PanelWarnaPengajar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Data Pengajar");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teacher (1).png"))); // NOI18N

        PanelWarnaPengajar2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaPengajar2Layout = new javax.swing.GroupLayout(PanelWarnaPengajar2);
        PanelWarnaPengajar2.setLayout(PanelWarnaPengajar2Layout);
        PanelWarnaPengajar2Layout.setHorizontalGroup(
            PanelWarnaPengajar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PanelWarnaPengajar2Layout.setVerticalGroup(
            PanelWarnaPengajar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDataPengajarLayout = new javax.swing.GroupLayout(PanelDataPengajar);
        PanelDataPengajar.setLayout(PanelDataPengajarLayout);
        PanelDataPengajarLayout.setHorizontalGroup(
            PanelDataPengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataPengajarLayout.createSequentialGroup()
                .addComponent(PanelWarnaPengajar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(PanelWarnaPengajar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelDataPengajarLayout.setVerticalGroup(
            PanelDataPengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataPengajarLayout.createSequentialGroup()
                .addGroup(PanelDataPengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDataPengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PanelWarnaPengajar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelWarnaPengajar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelDataPengajarLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel8)))
                    .addGroup(PanelDataPengajarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelDataPengajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 513, -1, 60));

        PanelDataAkun.setBackground(new java.awt.Color(255, 255, 255));
        PanelDataAkun.setForeground(new java.awt.Color(0, 0, 0));
        PanelDataAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDataAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDataAkunMouseClicked(evt);
            }
        });

        PanelWarnaKamar1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaKamar1Layout = new javax.swing.GroupLayout(PanelWarnaKamar1);
        PanelWarnaKamar1.setLayout(PanelWarnaKamar1Layout);
        PanelWarnaKamar1Layout.setHorizontalGroup(
            PanelWarnaKamar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        PanelWarnaKamar1Layout.setVerticalGroup(
            PanelWarnaKamar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Data Akun");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/akun (1).png"))); // NOI18N

        PanelWarnaKamar2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelWarnaKamar2Layout = new javax.swing.GroupLayout(PanelWarnaKamar2);
        PanelWarnaKamar2.setLayout(PanelWarnaKamar2Layout);
        PanelWarnaKamar2Layout.setHorizontalGroup(
            PanelWarnaKamar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PanelWarnaKamar2Layout.setVerticalGroup(
            PanelWarnaKamar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDataAkunLayout = new javax.swing.GroupLayout(PanelDataAkun);
        PanelDataAkun.setLayout(PanelDataAkunLayout);
        PanelDataAkunLayout.setHorizontalGroup(
            PanelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataAkunLayout.createSequentialGroup()
                .addComponent(PanelWarnaKamar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(PanelWarnaKamar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelDataAkunLayout.setVerticalGroup(
            PanelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataAkunLayout.createSequentialGroup()
                .addGroup(PanelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PanelWarnaKamar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelWarnaKamar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelDataAkunLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelDataAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 613, 370, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teksJudul.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        teksJudul.setForeground(new java.awt.Color(0, 0, 0));
        teksJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksJudul.setText("jLabel6");
        jPanel2.add(teksJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 910, 70));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setMinimumSize(new java.awt.Dimension(70, 30));
        jSeparator1.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 910, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setMinimumSize(new java.awt.Dimension(70, 30));
        jSeparator2.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 910, 20));

        PanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        PanelMenu.setLayout(new java.awt.CardLayout());
        jPanel2.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 910, 590));

        buttonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/minimize (1).png"))); // NOI18N
        buttonMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizeMouseClicked(evt);
            }
        });
        jPanel2.add(buttonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 4, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG OUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDashboardMouseClicked
        teksJudul.setText("Dashboard");
        
        PanelDashboard pds = new PanelDashboard();
        PanelWarnaDashboard1.setBackground(Color.BLACK);
        PanelWarnaDashboard2.setBackground(Color.BLACK);
        PanelWarnaSantri1.setBackground(Color.GRAY);
        PanelWarnaSantri2.setBackground(Color.GRAY);
        PanelWarnaWaliSantri1.setBackground(Color.GRAY);
        PanelWarnaWaliSantri2.setBackground(Color.GRAY);
        PanelWarnaPengajar1.setBackground(Color.GRAY);
        PanelWarnaPengajar2.setBackground(Color.GRAY);
        PanelWarnaKamar1.setBackground(Color.GRAY);
        PanelWarnaKamar2.setBackground(Color.GRAY);
        PanelMenu.removeAll();
        PanelMenu.repaint();
        PanelMenu.revalidate();
        PanelMenu.add(pds);
        PanelMenu.repaint();
        PanelMenu.revalidate();
    }//GEN-LAST:event_PanelDashboardMouseClicked

    private void PanelDataSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDataSantriMouseClicked
        teksJudul.setText("Data Santri");
        
        PanelDataSantri pds = new PanelDataSantri();
        PanelWarnaDashboard1.setBackground(Color.GRAY);
        PanelWarnaDashboard2.setBackground(Color.GRAY);
        PanelWarnaSantri1.setBackground(Color.black);
        PanelWarnaSantri2.setBackground(Color.black);
        PanelWarnaWaliSantri1.setBackground(Color.GRAY);
        PanelWarnaWaliSantri2.setBackground(Color.GRAY);
        PanelWarnaPengajar1.setBackground(Color.GRAY);
        PanelWarnaPengajar2.setBackground(Color.GRAY);
        PanelWarnaKamar1.setBackground(Color.GRAY);
        PanelWarnaKamar2.setBackground(Color.GRAY);
        PanelMenu.removeAll();
        PanelMenu.repaint();
        PanelMenu.revalidate();
        PanelMenu.add(pds);
        PanelMenu.repaint();
        PanelMenu.revalidate();
    }//GEN-LAST:event_PanelDataSantriMouseClicked

    private void PanelDataWaliSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDataWaliSantriMouseClicked
        teksJudul.setText("Data Wali Santri");
        
        PanelDataWaliSantri pdws = new PanelDataWaliSantri();
        PanelWarnaDashboard1.setBackground(Color.GRAY);
        PanelWarnaDashboard2.setBackground(Color.GRAY);
        PanelWarnaSantri1.setBackground(Color.GRAY);
        PanelWarnaSantri2.setBackground(Color.GRAY);
        PanelWarnaWaliSantri1.setBackground(Color.black);
        PanelWarnaWaliSantri2.setBackground(Color.black);
        PanelWarnaPengajar1.setBackground(Color.GRAY);
        PanelWarnaPengajar2.setBackground(Color.GRAY);
        PanelWarnaKamar1.setBackground(Color.GRAY);
        PanelWarnaKamar2.setBackground(Color.GRAY);
        PanelMenu.removeAll();
        PanelMenu.repaint();
        PanelMenu.revalidate();
        PanelMenu.add(pdws);
        PanelMenu.repaint();
        PanelMenu.revalidate();
    }//GEN-LAST:event_PanelDataWaliSantriMouseClicked

    private void PanelDataPengajarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDataPengajarMouseClicked
        teksJudul.setText("Data Pengajar");
        
        PanelDataPengajar pdp = new PanelDataPengajar();
        PanelWarnaDashboard1.setBackground(Color.GRAY);
        PanelWarnaDashboard2.setBackground(Color.GRAY);
        PanelWarnaSantri1.setBackground(Color.GRAY);
        PanelWarnaSantri2.setBackground(Color.GRAY);
        PanelWarnaWaliSantri1.setBackground(Color.GRAY);
        PanelWarnaWaliSantri2.setBackground(Color.GRAY);
        PanelWarnaPengajar1.setBackground(Color.black);
        PanelWarnaPengajar2.setBackground(Color.black);
        PanelWarnaKamar1.setBackground(Color.GRAY);
        PanelWarnaKamar2.setBackground(Color.GRAY);
        PanelMenu.removeAll();
        PanelMenu.repaint();
        PanelMenu.revalidate();
        PanelMenu.add(pdp);
        PanelMenu.repaint();
        PanelMenu.revalidate();
    }//GEN-LAST:event_PanelDataPengajarMouseClicked

    private void PanelDataAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDataAkunMouseClicked
        teksJudul.setText("Data Akun");
        
        PanelDataAkun pda = new PanelDataAkun();
        PanelWarnaDashboard1.setBackground(Color.GRAY);
        PanelWarnaDashboard2.setBackground(Color.GRAY);
        PanelWarnaSantri1.setBackground(Color.GRAY);
        PanelWarnaSantri2.setBackground(Color.GRAY);
        PanelWarnaWaliSantri1.setBackground(Color.GRAY);
        PanelWarnaWaliSantri2.setBackground(Color.GRAY);
        PanelWarnaPengajar1.setBackground(Color.GRAY);
        PanelWarnaPengajar2.setBackground(Color.GRAY);
        PanelWarnaKamar1.setBackground(Color.BLACK);
        PanelWarnaKamar2.setBackground(Color.BLACK);
        PanelMenu.removeAll();
        PanelMenu.repaint();
        PanelMenu.revalidate();
        PanelMenu.add(pda);
        PanelMenu.repaint();
        PanelMenu.revalidate();
    }//GEN-LAST:event_PanelDataAkunMouseClicked

    private void buttonMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_buttonMinimizeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Keluar",
                "KELUAR",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JPanel PanelDataAkun;
    private javax.swing.JPanel PanelDataPengajar;
    private javax.swing.JPanel PanelDataSantri;
    private javax.swing.JPanel PanelDataWaliSantri;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelWarnaDashboard1;
    private javax.swing.JPanel PanelWarnaDashboard2;
    private javax.swing.JPanel PanelWarnaKamar1;
    private javax.swing.JPanel PanelWarnaKamar2;
    private javax.swing.JPanel PanelWarnaPengajar1;
    private javax.swing.JPanel PanelWarnaPengajar2;
    private javax.swing.JPanel PanelWarnaSantri1;
    private javax.swing.JPanel PanelWarnaSantri2;
    private javax.swing.JPanel PanelWarnaWaliSantri1;
    private javax.swing.JPanel PanelWarnaWaliSantri2;
    private javax.swing.JLabel buttonMinimize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel teksJudul;
    // End of variables declaration//GEN-END:variables
}
