package Design;

import DAO.CrudAkun;
import Pesantren.Akun;
import Validasi.ValidasiInputan;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

public class FormLogin extends javax.swing.JFrame {

    // Membuat Objek
    Akun akun = new Akun();
    CrudAkun log = new CrudAkun();
    ValidasiInputan vld = new ValidasiInputan();

    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        teksUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        teksPass = new javax.swing.JPasswordField();
        buttonMata = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        buttonSignIn = new javax.swing.JButton();
        buttonSignUp = new javax.swing.JButton();
        buttonFP = new javax.swing.JLabel();
        ValidasiTeksUser = new javax.swing.JLabel();
        ValidasiTeksPass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonMinimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(650, 350));

        jPanel2.setBackground(new java.awt.Color(0, 155, 76));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/images (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        PanelLogin.setBackground(new java.awt.Color(250, 250, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 30));

        teksUser.setBackground(new java.awt.Color(250, 250, 250));
        teksUser.setForeground(new java.awt.Color(0, 0, 0));
        teksUser.setText("Username");
        teksUser.setBorder(null);
        teksUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksUserFocusLost(evt);
            }
        });
        teksUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksUserKeyReleased(evt);
            }
        });
        jPanel3.add(teksUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 20));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/padlock.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 30));

        teksPass.setBackground(new java.awt.Color(250, 250, 250));
        teksPass.setForeground(new java.awt.Color(0, 0, 0));
        teksPass.setText("Password");
        teksPass.setBorder(null);
        teksPass.setEchoChar('*');
        teksPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksPassFocusLost(evt);
            }
        });
        teksPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksPassKeyReleased(evt);
            }
        });
        jPanel3.add(teksPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 20));

        buttonMata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/eye.png"))); // NOI18N
        buttonMata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMataMouseClicked(evt);
            }
        });
        jPanel3.add(buttonMata, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 20));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 10));

        buttonSignIn.setBackground(new java.awt.Color(0, 155, 76));
        buttonSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSignIn.setForeground(new java.awt.Color(255, 255, 255));
        buttonSignIn.setText("SIGN IN");
        buttonSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSignInMouseExited(evt);
            }
        });
        buttonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignInActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        buttonSignUp.setBackground(new java.awt.Color(51, 51, 51));
        buttonSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSignUp.setForeground(new java.awt.Color(250, 250, 250));
        buttonSignUp.setText("SIGN UP");
        buttonSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSignUpMouseExited(evt);
            }
        });
        buttonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignUpActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        buttonFP.setForeground(new java.awt.Color(0, 0, 0));
        buttonFP.setText("Forgot Password ?");
        buttonFP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonFPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonFPMouseExited(evt);
            }
        });
        jPanel3.add(buttonFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        ValidasiTeksUser.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(ValidasiTeksUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        ValidasiTeksPass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(ValidasiTeksPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        buttonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/minimize (1).png"))); // NOI18N
        buttonMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(buttonMinimize)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
            .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMinimize))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teksUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksUserFocusGained
        if (teksUser.getText().equals("Username")) {
            teksUser.setText("");
        }
    }//GEN-LAST:event_teksUserFocusGained

    private void teksUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksUserFocusLost
        if (teksUser.getText().equals("")) {
            teksUser.setText("Username");
        }
    }//GEN-LAST:event_teksUserFocusLost

    private void teksPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksPassFocusGained
        if (teksPass.getText().equals("Password")) {
            teksPass.setText("");
        }
    }//GEN-LAST:event_teksPassFocusGained

    private void teksPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksPassFocusLost
        if (teksPass.getText().equals("")) {
            teksPass.setText("Password");
        }
    }//GEN-LAST:event_teksPassFocusLost
    boolean cek = true;
    private void buttonMataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMataMouseClicked
        if (cek) {
            teksPass.setEchoChar((char) 0);
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/hidden.png");
            buttonMata.setIcon(icon);
            cek = false;
        } else {
            teksPass.setEchoChar('\u002a');
            ImageIcon icon = new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\Bahasa Fundamental\\JAVA\\ProjekJava - Ahmad Faisal Hidayat\\src\\gambar\\eye.png");
            buttonMata.setIcon(icon);
            cek = true;
        }
    }//GEN-LAST:event_buttonMataMouseClicked

    private void buttonSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignInMouseEntered
        buttonSignIn.setForeground(Color.black);
    }//GEN-LAST:event_buttonSignInMouseEntered

    private void buttonSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignInMouseExited
        buttonSignIn.setForeground(Color.white);
    }//GEN-LAST:event_buttonSignInMouseExited

    private void buttonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignInActionPerformed
        akun.setUsername(teksUser.getText());
        akun.setPassword(teksPass.getText());

        if (log.login(akun) == 1 && vld.cekUsername(teksUser.getText()) == 0 && vld.cekPassword(teksPass.getText()) == 0) {
            JOptionPane.showMessageDialog(this, "Login Berhasil", "", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            FormMenu menu = new FormMenu();
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Login Gagal", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonSignInActionPerformed

    private void buttonSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignUpMouseEntered
        buttonSignUp.setForeground(Color.black);
    }//GEN-LAST:event_buttonSignUpMouseEntered

    private void buttonSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignUpMouseExited
        buttonSignUp.setForeground(Color.white);
    }//GEN-LAST:event_buttonSignUpMouseExited

    private void buttonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignUpActionPerformed
        this.dispose();
        new FormSignUp().setVisible(true);
    }//GEN-LAST:event_buttonSignUpActionPerformed

    private void buttonFPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFPMouseEntered
        buttonFP.setForeground(Color.blue);
    }//GEN-LAST:event_buttonFPMouseEntered

    private void buttonFPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFPMouseExited
        buttonFP.setForeground(Color.black);
    }//GEN-LAST:event_buttonFPMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Keluar",
                "KELUAR",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void buttonFPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFPMouseClicked
        this.dispose();
        new FormLupaPassword().setVisible(true);
    }//GEN-LAST:event_buttonFPMouseClicked

    private void teksUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksUserKeyReleased
        if (teksUser.getText().length() < 6) {
            ValidasiTeksUser.setText("Minimal 6 Karakter");
        } else if (teksUser.getText().length() > 30) {
            ValidasiTeksUser.setText("Minimal 30 Karakter");
        } else {
            ValidasiTeksUser.setText("");
        }

        if (vld.cekUsername(teksUser.getText()) != 0) {
            ValidasiTeksUser.setText("Masukan Data Dengan Benar");
        }
    }//GEN-LAST:event_teksUserKeyReleased

    private void teksPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksPassKeyReleased
        if (teksPass.getText().length() < 6) {
            ValidasiTeksPass.setText("Minimal 6 Karakter");
        } else if (teksPass.getText().length() > 25) {
            ValidasiTeksPass.setText("Maksimal 25 Karakter");
        } else {
            ValidasiTeksPass.setText("");
        }

        if (vld.cekPassword(teksPass.getText()) != 0) {
            ValidasiTeksPass.setText("Masukan Data Dengan Benar");
        }
    }//GEN-LAST:event_teksPassKeyReleased

    private void buttonMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_buttonMinimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel ValidasiTeksPass;
    private javax.swing.JLabel ValidasiTeksUser;
    private javax.swing.JLabel buttonFP;
    private javax.swing.JLabel buttonMata;
    private javax.swing.JLabel buttonMinimize;
    private javax.swing.JButton buttonSignIn;
    private javax.swing.JButton buttonSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField teksPass;
    private javax.swing.JTextField teksUser;
    // End of variables declaration//GEN-END:variables
}
