package Design;

import DAO.CrudAkun;
import Pesantren.Akun;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

public class PanelDataAkun extends javax.swing.JPanel {

    CrudAkun cruda = new CrudAkun();
    Akun akun = new Akun();

    public PanelDataAkun() {
        initComponents();
        buttonHapus.setEnabled(false);
        tableAkun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonHapus = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        teksSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JLabel();
        buttonFilter = new javax.swing.JButton();
        teksID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teksUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        teksPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAkun = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHapus.setBackground(new java.awt.Color(255, 0, 0));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete (1).png"))); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHapusMouseExited(evt);
            }
        });
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 40));

        buttonReset.setBackground(new java.awt.Color(102, 102, 102));
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reset (1).png"))); // NOI18N
        buttonReset.setText("RESET");
        buttonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonResetMouseExited(evt);
            }
        });
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });
        jPanel1.add(buttonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 40));

        teksSearch.setBackground(new java.awt.Color(255, 255, 255));
        teksSearch.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksSearch.setForeground(new java.awt.Color(0, 0, 0));
        teksSearch.setText("Search...");
        teksSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksSearchFocusLost(evt);
            }
        });
        jPanel1.add(teksSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 360, 30));

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search (1).png"))); // NOI18N
        buttonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchMouseClicked(evt);
            }
        });
        jPanel1.add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, 50));

        buttonFilter.setBackground(new java.awt.Color(153, 153, 153));
        buttonFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonFilter.setForeground(new java.awt.Color(255, 255, 255));
        buttonFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FILTER (1).png"))); // NOI18N
        buttonFilter.setText("FILTER");
        buttonFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonFilterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonFilterMouseExited(evt);
            }
        });
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, 40));

        teksID.setBackground(new java.awt.Color(255, 255, 255));
        teksID.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksID.setForeground(new java.awt.Color(0, 0, 0));
        teksID.setText("null");
        teksID.setEnabled(false);
        jPanel1.add(teksID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 450, 30));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        teksUsername.setBackground(new java.awt.Color(255, 255, 255));
        teksUsername.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksUsername.setForeground(new java.awt.Color(0, 0, 0));
        teksUsername.setText("null");
        teksUsername.setEnabled(false);
        jPanel1.add(teksUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 450, 30));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        teksPassword.setBackground(new java.awt.Color(255, 255, 255));
        teksPassword.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksPassword.setForeground(new java.awt.Color(0, 0, 0));
        teksPassword.setText("null");
        teksPassword.setEnabled(false);
        jPanel1.add(teksPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 450, 30));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        tableAkun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAkunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAkun);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 910, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHapusMouseEntered
        if (buttonHapus.isEnabled()) {
            buttonHapus.setForeground(Color.black);
        }
    }//GEN-LAST:event_buttonHapusMouseEntered

    private void buttonHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHapusMouseExited
        if (buttonHapus.isEnabled()) {
            buttonHapus.setForeground(Color.white);
        }
    }//GEN-LAST:event_buttonHapusMouseExited

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
            "Anda Ingin Menghapus Data Akun?",
            "Hapus Akun",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksID.getText().equals("AUTO INCREMENT")) {
                System.out.println("ID Tidak Ditemukan");
            } else {
                akun.setId(teksID.getText());
                if (cruda.hapusAkun(akun) == 1) {
                    tableAkun();
                    JOptionPane.showMessageDialog(this, "Data Akun Berhasil Dihapus", "", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Akun Gagal Dihapus", "", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseEntered
        buttonReset.setForeground(Color.black);
    }//GEN-LAST:event_buttonResetMouseEntered

    private void buttonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseExited
        buttonReset.setForeground(Color.white);
    }//GEN-LAST:event_buttonResetMouseExited

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        teksID.setText("null");
        teksUsername.setText("null");
        teksPassword.setText("null");
        teksSearch.setText("Search...");
        buttonHapus.setEnabled(false);
        tableAkun();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void teksSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksSearchFocusGained
        if (teksSearch.getText().equals("Search...")) {
            teksSearch.setText("");
        }
    }//GEN-LAST:event_teksSearchFocusGained

    private void teksSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksSearchFocusLost
        if (teksSearch.getText().isEmpty()) {
            teksSearch.setText("Search...");
        }
    }//GEN-LAST:event_teksSearchFocusLost

    private void buttonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchMouseClicked
        String by = teksSearch.getText();
        tableAkun.setModel(cruda.cariPengajar(by));
    }//GEN-LAST:event_buttonSearchMouseClicked

    private void buttonFilterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFilterMouseEntered
        buttonFilter.setForeground(Color.black);
    }//GEN-LAST:event_buttonFilterMouseEntered

    private void buttonFilterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFilterMouseExited
        buttonFilter.setForeground(Color.white);
    }//GEN-LAST:event_buttonFilterMouseExited

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        Component source = (Component) evt.getSource();
        Object urut = JOptionPane.showInputDialog(source,
            "Pilih Salah Satu",
            "Urut Berdasarkan?", JOptionPane.QUESTION_MESSAGE,
            null, new String[]{"ID", "NAMA"}, "ID");
        Object order = JOptionPane.showInputDialog(source,
            "Pilih Salah Satu",
            "Order By", JOptionPane.QUESTION_MESSAGE,
            null, new String[]{"ASC", "DESC"}, "ASC");
        tableAkun.setModel(cruda.filterAkun((String) urut, (String) order));
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void tableAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAkunMouseClicked
        int baris = tableAkun.getSelectedRow();
        teksID.setText(tableAkun.getModel().getValueAt(baris, 0).toString());
        teksUsername.setText(tableAkun.getModel().getValueAt(baris, 1).toString());
        teksPassword.setText(tableAkun.getModel().getValueAt(baris, 2).toString());
        buttonHapus.setEnabled(true);
    }//GEN-LAST:event_tableAkunMouseClicked

    public void tableAkun() {
        tableAkun.setModel(cruda.tampilAkun());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JLabel buttonSearch;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAkun;
    private javax.swing.JTextField teksID;
    private javax.swing.JTextField teksPassword;
    private javax.swing.JTextField teksSearch;
    private javax.swing.JTextField teksUsername;
    // End of variables declaration//GEN-END:variables
}
