package Design;

import DAO.CrudSantri;
import Pesantren.Santri;
import Validasi.ValidasiInputan;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PanelDataSantri extends javax.swing.JPanel {

    CrudSantri cruds = new CrudSantri();
    Santri santri = new Santri();
    ValidasiInputan vld = new ValidasiInputan();

    public PanelDataSantri() {
        initComponents();
        tableSantri();
        buttonEdit.setEnabled(false);
        buttonHapus.setEnabled(false);
    }

    public void tableSantri() {
        tableSantri.setModel(cruds.tampilSantri());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSantri = new javax.swing.JTable();
        buttonTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        teksNis = new javax.swing.JTextField();
        teksNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teksJK = new javax.swing.JComboBox<>();
        teksTTL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teksNamaAyah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teksNamaIbu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teksAlamat = new javax.swing.JTextArea();
        cekValidasiNIS = new javax.swing.JLabel();
        validasiTeksNis = new javax.swing.JLabel();
        cekValidasiNama = new javax.swing.JLabel();
        validasiTeksNama = new javax.swing.JLabel();
        validasiTeksTTL = new javax.swing.JLabel();
        validasiTeksNamaAyah = new javax.swing.JLabel();
        validasiTeksNamaIbu = new javax.swing.JLabel();
        validasiTeksAlamat = new javax.swing.JLabel();
        cekValidasiTTL = new javax.swing.JLabel();
        cekValidasiNamaAyah = new javax.swing.JLabel();
        cekValidasiNamaIbu = new javax.swing.JLabel();
        cekValidasiAlamat = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        teksSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonFilter = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        TTLChooser = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableSantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSantri.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSantriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSantri);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 292, 910, 310));

        buttonTambah.setBackground(new java.awt.Color(51, 255, 0));
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add (1).png"))); // NOI18N
        buttonTambah.setText("TAMBAH");
        buttonTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonTambahMouseExited(evt);
            }
        });
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 40));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        teksNis.setBackground(new java.awt.Color(255, 255, 255));
        teksNis.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNis.setForeground(new java.awt.Color(0, 0, 0));
        teksNis.setText("Masukan NIS...");
        teksNis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        teksNis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNisFocusLost(evt);
            }
        });
        teksNis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNisKeyReleased(evt);
            }
        });
        jPanel1.add(teksNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 300, 30));

        teksNama.setBackground(new java.awt.Color(255, 255, 255));
        teksNama.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNama.setForeground(new java.awt.Color(0, 0, 0));
        teksNama.setText("Masukan Nama...");
        teksNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNamaFocusLost(evt);
            }
        });
        teksNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNamaKeyReleased(evt);
            }
        });
        jPanel1.add(teksNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 300, 30));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jenis Kelamin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        teksJK.setBackground(new java.awt.Color(255, 255, 255));
        teksJK.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksJK.setForeground(new java.awt.Color(0, 0, 0));
        teksJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAKI-LAKI", "PEREMPUAN" }));
        jPanel1.add(teksJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 300, 30));

        teksTTL.setBackground(new java.awt.Color(255, 255, 255));
        teksTTL.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksTTL.setForeground(new java.awt.Color(0, 0, 0));
        teksTTL.setText("Masukan Daerah...");
        teksTTL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksTTLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksTTLFocusLost(evt);
            }
        });
        teksTTL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksTTLKeyReleased(evt);
            }
        });
        jPanel1.add(teksTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, 30));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TTL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        teksNamaAyah.setBackground(new java.awt.Color(255, 255, 255));
        teksNamaAyah.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNamaAyah.setForeground(new java.awt.Color(0, 0, 0));
        teksNamaAyah.setText("Masukan Nama Ayah...");
        teksNamaAyah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNamaAyahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNamaAyahFocusLost(evt);
            }
        });
        teksNamaAyah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNamaAyahKeyReleased(evt);
            }
        });
        jPanel1.add(teksNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 300, 30));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ayah");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 30));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, 30));

        teksNamaIbu.setBackground(new java.awt.Color(255, 255, 255));
        teksNamaIbu.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNamaIbu.setForeground(new java.awt.Color(0, 0, 0));
        teksNamaIbu.setText("Masukan Nama Ibu...");
        teksNamaIbu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNamaIbuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNamaIbuFocusLost(evt);
            }
        });
        teksNamaIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNamaIbuKeyReleased(evt);
            }
        });
        jPanel1.add(teksNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 300, 30));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ibu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 30));

        teksAlamat.setBackground(new java.awt.Color(255, 255, 255));
        teksAlamat.setColumns(20);
        teksAlamat.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksAlamat.setForeground(new java.awt.Color(0, 0, 0));
        teksAlamat.setLineWrap(true);
        teksAlamat.setRows(5);
        teksAlamat.setText("Masukan Alamat...");
        teksAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksAlamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksAlamatFocusLost(evt);
            }
        });
        teksAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksAlamatKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(teksAlamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 300, 110));

        cekValidasiNIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 30));

        validasiTeksNis.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNis.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        cekValidasiNama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 30));

        validasiTeksNama.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNama.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 300, 10));

        validasiTeksTTL.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksTTL.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 300, 10));

        validasiTeksNamaAyah.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNamaAyah.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 300, 10));

        validasiTeksNamaIbu.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNamaIbu.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 300, 10));

        validasiTeksAlamat.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksAlamat.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 300, 10));

        cekValidasiTTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 30));

        cekValidasiNamaAyah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, 30));

        cekValidasiNamaIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, 30));

        cekValidasiAlamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, 90));

        buttonEdit.setBackground(new java.awt.Color(0, 255, 204));
        buttonEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit (1).png"))); // NOI18N
        buttonEdit.setText("EDIT");
        buttonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEditMouseExited(evt);
            }
        });
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 40));

        buttonHapus.setBackground(new java.awt.Color(255, 0, 0));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete (1).png"))); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHapusMouseExited(evt);
            }
        });
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, 40));

        teksSearch.setBackground(new java.awt.Color(255, 255, 255));
        teksSearch.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksSearch.setForeground(new java.awt.Color(0, 0, 0));
        teksSearch.setText("Search...");
        teksSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksSearchFocusLost(evt);
            }
        });
        jPanel1.add(teksSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 260, 30));

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search (1).png"))); // NOI18N
        buttonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchMouseClicked(evt);
            }
        });
        jPanel1.add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 220, -1));

        buttonFilter.setBackground(new java.awt.Color(153, 153, 153));
        buttonFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonFilter.setForeground(new java.awt.Color(255, 255, 255));
        buttonFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FILTER (1).png"))); // NOI18N
        buttonFilter.setText("FILTER");
        buttonFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonFilterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonFilterMouseExited(evt);
            }
        });
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, 40));

        buttonReset.setBackground(new java.awt.Color(102, 102, 102));
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reset (1).png"))); // NOI18N
        buttonReset.setText("RESET");
        buttonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonResetMouseExited(evt);
            }
        });
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });
        jPanel1.add(buttonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, 40));
        jPanel1.add(TTLChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 160, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahMouseEntered
        buttonTambah.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonTambahMouseEntered

    private void buttonTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahMouseExited
        buttonTambah.setForeground(Color.white);
    }//GEN-LAST:event_buttonTambahMouseExited

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Menambahkan Data Santri?",
                "Tambah Santri",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksNis.getText().equals("Masukan NIS...") || teksNama.getText().equals("Masukan Nama...") || teksTTL.getText().equals("Masukan TTL...") || teksNamaAyah.getText().equals("Masukan Nama Ayah...") || teksNamaIbu.getText().equals("Masukan Nama Ibu...") || teksAlamat.getText().equals("Masukan Alamat...")) {
                JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar", "", JOptionPane.WARNING_MESSAGE);
            } else {
                String tampilan = "YYYY-MM-dd";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);

                santri.setNis(teksNis.getText());
                santri.setNama(teksNama.getText().toUpperCase());
                santri.setJenisKelamin((String) teksJK.getSelectedItem());
                santri.setTtlDaerah(teksTTL.getText().toUpperCase());
                santri.setDateChooser(String.valueOf(fm.format(TTLChooser.getDate())));
                santri.setAyah(teksNamaAyah.getText().toUpperCase());
                santri.setIbu(teksNamaIbu.getText().toUpperCase());
                santri.setAlamat(teksAlamat.getText().toUpperCase());

                if (cruds.validasiSantri(santri) == 0) {
                    if (cruds.tambahSantri(santri) == 1 && vld.cekNIS(teksNis.getText()) == 0 && vld.cekNama(teksNama.getText()) == 0 && vld.cekNama(teksNamaAyah.getText()) == 0 && vld.cekNama(teksNamaIbu.getText()) == 0 && vld.cekAlamat(teksAlamat.getText()) == 0) {
                        JOptionPane.showMessageDialog(this, "Data Santri Berhasil Ditambahkan", "", JOptionPane.INFORMATION_MESSAGE);
                        tableSantri();
                    } else {
                        JOptionPane.showMessageDialog(this, "Data Santri Gagal Ditambahkan", "", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Nama Sudah Terdaftar", "", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void teksNisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNisFocusGained
        if (teksNis.getText().equals("Masukan NIS...")) {
            teksNis.setText("");
        }
    }//GEN-LAST:event_teksNisFocusGained

    private void teksNisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNisFocusLost
        if (teksNis.getText().equals("")) {
            teksNis.setText("Masukan NIS...");
        }
    }//GEN-LAST:event_teksNisFocusLost

    private void teksNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaFocusGained
        if (teksNama.getText().equals("Masukan Nama...")) {
            teksNama.setText("");
        }
    }//GEN-LAST:event_teksNamaFocusGained

    private void teksNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaFocusLost
        if (teksNama.getText().equals("")) {
            teksNama.setText("Masukan Nama...");
            validasiTeksNama.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNama.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaFocusLost

    private void teksNamaAyahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaAyahFocusGained
        if (teksNamaAyah.getText().equals("Masukan Nama Ayah...")) {
            teksNamaAyah.setText("");
        }
    }//GEN-LAST:event_teksNamaAyahFocusGained

    private void teksNamaAyahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaAyahFocusLost
        if (teksNamaAyah.getText().equals("")) {
            teksNamaAyah.setText("Masukan Nama Ayah...");
            validasiTeksNamaAyah.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaAyahFocusLost

    private void teksNamaIbuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaIbuFocusGained
        if (teksNamaIbu.getText().equals("Masukan Nama Ibu...")) {
            teksNamaIbu.setText("");
        }
    }//GEN-LAST:event_teksNamaIbuFocusGained

    private void teksNamaIbuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaIbuFocusLost
        if (teksNamaIbu.getText().equals("")) {
            teksNamaIbu.setText("Masukan Nama Ibu...");
            validasiTeksNamaIbu.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaIbuFocusLost

    private void teksAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksAlamatFocusGained
        if (teksAlamat.getText().equals("Masukan Alamat...")) {
            teksAlamat.setText("");
        }
    }//GEN-LAST:event_teksAlamatFocusGained

    private void teksAlamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksAlamatFocusLost
        if (teksAlamat.getText().equals("")) {
            teksAlamat.setText("Masukan Alamat...");
            validasiTeksAlamat.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiAlamat.setIcon(icon);
        }
    }//GEN-LAST:event_teksAlamatFocusLost

    private void teksNisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNisKeyReleased
        if (teksNis.getText().length() > 0 && teksNis.getText().length() < 5) {
            validasiTeksNis.setText("NIS harus 5 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNIS.setIcon(icon);
        } else if (teksNis.getText().length() > 5) {
            validasiTeksNis.setText("NIS harus 5 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNIS.setIcon(icon);
        } else {
            validasiTeksNis.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNIS.setIcon(icon);
        }

        if (vld.cekNIS(teksNis.getText()) != 0) {
            validasiTeksNis.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNIS.setIcon(icon);
        }
    }//GEN-LAST:event_teksNisKeyReleased

    private void teksNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNamaKeyReleased
        if (!teksNama.getText().contains(" ")) {
            validasiTeksNama.setText("Nama Minimal Terdiri Dari 2 Kata");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNama.setIcon(icon);
        } else if (teksNama.getText().length() > 60) {
            validasiTeksNama.setText("Maksimal 60 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNama.setIcon(icon);
        } else if (teksNama.getText().length() < 10) {
            validasiTeksNama.setText("Minimal 10 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNama.setIcon(icon);
        } else {
            validasiTeksNama.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNama.setIcon(icon);
        }

        if (vld.cekNama(teksNama.getText()) != 0) {
            validasiTeksNama.setText("Masukan Data Dengan Benar");
        }
    }//GEN-LAST:event_teksNamaKeyReleased

    private void teksTTLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksTTLFocusLost
        if (teksTTL.getText().equals("")) {
            teksTTL.setText("Masukan Daerah...");
        }
    }//GEN-LAST:event_teksTTLFocusLost

    private void teksTTLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksTTLFocusGained
        if (teksTTL.getText().equals("Masukan Daerah...")) {
            teksTTL.setText("");
        }
    }//GEN-LAST:event_teksTTLFocusGained

    private void teksTTLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksTTLKeyReleased
        if (vld.cekHuruf(teksTTL.getText()) != 0) {
            validasiTeksTTL.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiTTL.setIcon(icon);
        } else {
            validasiTeksTTL.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiTTL.setIcon(icon);
        }
    }//GEN-LAST:event_teksTTLKeyReleased

    private void teksNamaAyahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNamaAyahKeyReleased
        if (!teksNamaAyah.getText().contains(" ")) {
            validasiTeksNamaAyah.setText("Nama Minimal Terdiri Dari 2 Kata");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        } else if (teksNamaAyah.getText().length() > 60) {
            validasiTeksNamaAyah.setText("Maksimal 60 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        } else if (teksNamaAyah.getText().length() < 10) {
            validasiTeksNamaAyah.setText("Minimal 10 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        } else {
            validasiTeksNamaAyah.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        }

        if (vld.cekNama(teksNamaAyah.getText()) != 0) {
            validasiTeksNamaAyah.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaAyahKeyReleased

    private void teksNamaIbuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNamaIbuKeyReleased
        if (!teksNamaIbu.getText().contains(" ")) {
            validasiTeksNamaIbu.setText("Nama Minimal Terdiri Dari 2 Kata");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        } else if (teksNamaIbu.getText().length() > 60) {
            validasiTeksNamaIbu.setText("Maksimal 60 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        } else if (teksNamaIbu.getText().length() < 10) {
            validasiTeksNamaIbu.setText("Minimal 10 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        } else {
            validasiTeksNamaIbu.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        }

        if (vld.cekNama(teksNamaIbu.getText()) != 0) {
            validasiTeksNamaIbu.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaIbuKeyReleased

    private void teksAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksAlamatKeyReleased
        if (teksAlamat.getText().length() < 5) {
            validasiTeksAlamat.setText("Minimal 5 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiAlamat.setIcon(icon);
        } else if (teksAlamat.getText().length() > 60) {
            validasiTeksAlamat.setText("Maksimal 60 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiAlamat.setIcon(icon);
        } else {
            validasiTeksAlamat.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiAlamat.setIcon(icon);
        }

        if (vld.cekAlamat(teksAlamat.getText()) != 0) {
            validasiTeksAlamat.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiAlamat.setIcon(icon);
        }
    }//GEN-LAST:event_teksAlamatKeyReleased

    private void buttonEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseEntered
        if (buttonEdit.isEnabled()) {
            buttonEdit.setForeground(Color.black);
        }
    }//GEN-LAST:event_buttonEditMouseEntered

    private void buttonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseExited
        if (buttonEdit.isEnabled()) {
            buttonEdit.setForeground(Color.white);
        }
    }//GEN-LAST:event_buttonEditMouseExited

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Mengedit Data Santri?",
                "Edit Santri",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksNis.getText().equals("Masukan NIS...") || teksNama.getText().equals("Masukan Nama...") || teksTTL.getText().equals("Masukan TTL...") || teksNamaAyah.getText().equals("Masukan Nama Ayah...") || teksNamaIbu.getText().equals("Masukan Nama Ibu...") || teksAlamat.getText().equals("Masukan Alamat...")) {
                JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar", "", JOptionPane.WARNING_MESSAGE);
            } else {
                String tampilan = "YYYY-MM-dd";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);

                santri.setNis(teksNis.getText());
                santri.setNama(teksNama.getText().toUpperCase());
                santri.setJenisKelamin((String) teksJK.getSelectedItem());
                santri.setTtlDaerah(teksTTL.getText().toUpperCase());
                santri.setDateChooser(String.valueOf(fm.format(TTLChooser.getDate())));
                santri.setAyah(teksNamaAyah.getText().toUpperCase());
                santri.setIbu(teksNamaIbu.getText().toUpperCase());
                santri.setAlamat(teksAlamat.getText().toUpperCase());

                if (cruds.editSantri(santri) == 1 && vld.cekNIS(teksNis.getText()) == 0 && vld.cekNama(teksNama.getText()) == 0 && vld.cekNama(teksNamaAyah.getText()) == 0 && vld.cekNama(teksNamaIbu.getText()) == 0 && vld.cekAlamat(teksAlamat.getText()) == 0) {
                    JOptionPane.showMessageDialog(this, "Data Santri Berhasil Diedit", "", JOptionPane.INFORMATION_MESSAGE);
                    tableSantri();
                } else {
                    JOptionPane.showMessageDialog(this, "Data Santri Gagal Diedit", "", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHapusMouseEntered
        if (buttonHapus.isEnabled()) {
            buttonHapus.setForeground(Color.black);
        }
    }//GEN-LAST:event_buttonHapusMouseEntered

    private void buttonHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHapusMouseExited
        if (buttonHapus.isEnabled()) {
            buttonHapus.setForeground(Color.white);
        }
    }//GEN-LAST:event_buttonHapusMouseExited

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Menghapus Data Santri?",
                "Hapus Santri",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksNis.getText().isEmpty()) {
                System.out.println("NIS Masih Kosong!!!");
            } else {
                santri.setNis(teksNis.getText());
                if (cruds.hapusSantri(santri) == 1) {
                    tableSantri();
                    JOptionPane.showMessageDialog(this, "Data Santri Berhasil Dihapus", "", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Santri Gagal Dihapus", "", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tableSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSantriMouseClicked
        buttonTambah.setEnabled(false);
        buttonEdit.setEnabled(true);
        buttonHapus.setEnabled(true);

        int baris = tableSantri.getSelectedRow();
        teksNis.setText(tableSantri.getModel().getValueAt(baris, 0).toString());
        teksNama.setText(tableSantri.getModel().getValueAt(baris, 1).toString());
        
        if (tableSantri.getModel().getValueAt(baris, 2).toString().equalsIgnoreCase("laki-laki")) {
            teksJK.setSelectedIndex(0);
        } else {
            teksJK.setSelectedIndex(1);
        }
        
        String [] tamp = tableSantri.getModel().getValueAt(baris, 3).toString().split(", ");
        teksTTL.setText(tamp[0]);
        
        String date = tamp[1];
        java.util.Date date2;
        try {
            date2 = new SimpleDateFormat("yyyy-mm-dd").parse(date);
            TTLChooser.setDate(date2);
        } catch (ParseException ex) {
            Logger.getLogger(PanelDataSantri.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        teksAlamat.setText(tableSantri.getModel().getValueAt(baris, 4).toString());
        teksNamaAyah.setText(tableSantri.getModel().getValueAt(baris, 5).toString());
        teksNamaIbu.setText(tableSantri.getModel().getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tableSantriMouseClicked

    private void teksSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksSearchFocusGained
        if (teksSearch.getText().equals("Search...")) {
            teksSearch.setText("");
        }
    }//GEN-LAST:event_teksSearchFocusGained

    private void teksSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksSearchFocusLost
        if (teksSearch.getText().isEmpty()) {
            teksSearch.setText("Search...");
        }
    }//GEN-LAST:event_teksSearchFocusLost

    private void buttonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchMouseClicked
        String by = teksSearch.getText();
        tableSantri.setModel(cruds.cariSantri(by));
    }//GEN-LAST:event_buttonSearchMouseClicked

    private void buttonFilterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFilterMouseEntered
        buttonFilter.setForeground(Color.black);
    }//GEN-LAST:event_buttonFilterMouseEntered

    private void buttonFilterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFilterMouseExited
        buttonFilter.setForeground(Color.white);
    }//GEN-LAST:event_buttonFilterMouseExited

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        Component source = (Component) evt.getSource();
        Object urut = JOptionPane.showInputDialog(source,
            "Pilih Salah Satu",
            "Urut Berdasarkan?", JOptionPane.QUESTION_MESSAGE,
            null, new String[] { "NIS", "NAMA","AYAH", "IBU"},"NIS");
        Object order = JOptionPane.showInputDialog(source,
            "Pilih Salah Satu",
            "Order By", JOptionPane.QUESTION_MESSAGE,
            null, new String[] { "ASC", "DESC" },"ASC");
        tableSantri.setModel(cruds.filterSantri((String) urut,(String) order));
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void buttonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseEntered
        buttonReset.setForeground(Color.black);
    }//GEN-LAST:event_buttonResetMouseEntered

    private void buttonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseExited
        buttonReset.setForeground(Color.white);
    }//GEN-LAST:event_buttonResetMouseExited

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        buttonTambah.setEnabled(true);
        buttonEdit.setEnabled(false);
        buttonHapus.setEnabled(false);
        
        teksNis.setText("Masukan NIS...");
        teksNama.setText("Masukan Nama...");
        teksJK.setSelectedIndex(0);
        TTLChooser.setDate(null);
        teksTTL.setText("Masukan Daerah...");
        teksNamaAyah.setText("Masukan Nama Ayah...");
        teksNamaIbu.setText("Masukan Nama Ibu...");
        teksAlamat.setText("Masukan Alamat...");
        teksSearch.setText("Search...");
        tableSantri();
    }//GEN-LAST:event_buttonResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TTLChooser;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JLabel buttonSearch;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel cekValidasiAlamat;
    private javax.swing.JLabel cekValidasiNIS;
    private javax.swing.JLabel cekValidasiNama;
    private javax.swing.JLabel cekValidasiNamaAyah;
    private javax.swing.JLabel cekValidasiNamaIbu;
    private javax.swing.JLabel cekValidasiTTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableSantri;
    private javax.swing.JTextArea teksAlamat;
    private javax.swing.JComboBox<String> teksJK;
    private javax.swing.JTextField teksNama;
    private javax.swing.JTextField teksNamaAyah;
    private javax.swing.JTextField teksNamaIbu;
    private javax.swing.JTextField teksNis;
    private javax.swing.JTextField teksSearch;
    private javax.swing.JTextField teksTTL;
    private javax.swing.JLabel validasiTeksAlamat;
    private javax.swing.JLabel validasiTeksNama;
    private javax.swing.JLabel validasiTeksNamaAyah;
    private javax.swing.JLabel validasiTeksNamaIbu;
    private javax.swing.JLabel validasiTeksNis;
    private javax.swing.JLabel validasiTeksTTL;
    // End of variables declaration//GEN-END:variables
}
