package Design;

import DAO.CrudPengajar;
import DAO.CrudSantri;

public class PanelDashboard extends javax.swing.JPanel {

    CrudSantri cruds = new CrudSantri();
    CrudPengajar crudp = new CrudPengajar();

    public PanelDashboard() {
        initComponents();
        
        jumlahSantriIkhwan();
        jumlahSantriAkhwat();
        jumlahUstadz();
        jumlahUstadzah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        teksJUSTZ = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teksJSA = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelSantriIkhwan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        teksJSI = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        teksJUST = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 187, 187), 2, true));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teacher female (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, 70, 60));

        teksJUSTZ.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        teksJUSTZ.setForeground(new java.awt.Color(0, 0, 0));
        teksJUSTZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksJUSTZ.setText("ORANG");
        jPanel1.add(teksJUSTZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 130, 180, -1));

        jLabel4.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ustadzah");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("JUMLAH:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 190, 180));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 187, 187), 2, true));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/student female (1).png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 64, -1));

        jLabel7.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SANTRI");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        teksJSA.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        teksJSA.setForeground(new java.awt.Color(0, 0, 0));
        teksJSA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksJSA.setText("ORANG");
        jPanel2.add(teksJSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 130, 180, -1));

        jLabel9.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("akhwat");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("JUMLAH:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 190, 180));

        panelSantriIkhwan.setBackground(new java.awt.Color(204, 204, 204));
        panelSantriIkhwan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 187, 187), 2, true));
        panelSantriIkhwan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelSantriIkhwan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/student male (1).png"))); // NOI18N
        jLabel11.setText("jLabel1");
        panelSantriIkhwan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 64, -1));

        jLabel12.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("SANTRI");
        panelSantriIkhwan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        teksJSI.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        teksJSI.setForeground(new java.awt.Color(0, 0, 0));
        teksJSI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksJSI.setText("ORANG");
        panelSantriIkhwan.add(teksJSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 130, 180, -1));

        jLabel14.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("IKHWAN");
        panelSantriIkhwan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("JUMLAH:");
        panelSantriIkhwan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        add(panelSantriIkhwan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 180));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(187, 187, 187), 2, true));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/teacher male (1).png"))); // NOI18N
        jLabel16.setText("jLabel1");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 60, -1));

        teksJUST.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        teksJUST.setForeground(new java.awt.Color(0, 0, 0));
        teksJUST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teksJUST.setText("ORANG");
        jPanel4.add(teksJUST, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 130, 180, -1));

        jLabel19.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("ustadz");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("JUMLAH:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 190, 180));

        jLabel17.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Visi & Misi Pondok Pesantren Technopreneur As-Shofa");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 590, -1));

        jLabel21.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("MISI");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 580, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setText("- Menggelorakan semangat menuntut ilmu agama di semua kalangan.\n- Mencetak santri yang berkualitas dalam Pendidikan Al Qur’an,\n  Kitab kuning dan  Digital Teknologi.\n- Mengembangkan dan melestarikan ilmu-ilmu agama Islam yang  \n  dalam Al Quran, Hadits dan kitab-kitab kuning.\n- Memberi kesempatan menuntut ilmu kepada anak yatim, kaum dhu’afa \n  dan para muallaf.\n- Mencetak santri masa depan sebagai kader penerus perjuangan Ulama \n  dalam membela Bangsa dan Negara.");
        jTextArea1.setMargin(new java.awt.Insets(4, 6, 4, 6));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 520, 180));

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("VISI");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 580, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(1);
        jTextArea2.setText("“Menjadi Lembaga Pendidikan Islam Yang Membentuk Santri Berprestasi \nDan Berakhlakul Karimah, Ahli Al-Qur’an, Kitab Kuning  Dan Teknologi”");
        jTextArea2.setMargin(new java.awt.Insets(4, 6, 4, 6));
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 520, 70));
    }// </editor-fold>//GEN-END:initComponents

    
    public void jumlahSantriIkhwan() {
        int jumlah = cruds.hitungSantriIkhwan();
        teksJSI.setText(jumlah + " ORANG");
    }
    
    public void jumlahSantriAkhwat() {
        int jumlah = cruds.hitungSantriAkhwat();
        teksJSA.setText(jumlah + " ORANG");
    }
    
    public void jumlahUstadz() {
        int jumlah = crudp.hitungUstadz();
        teksJUST.setText(jumlah + " ORANG");
    }
    
    public void jumlahUstadzah() {
        int jumlah = crudp.hitungUstadzah();
        teksJUSTZ.setText(jumlah + " ORANG");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panelSantriIkhwan;
    private javax.swing.JLabel teksJSA;
    private javax.swing.JLabel teksJSI;
    private javax.swing.JLabel teksJUST;
    private javax.swing.JLabel teksJUSTZ;
    // End of variables declaration//GEN-END:variables
}
