package Design;

import DAO.CrudWaliSantri;
import Pesantren.WaliSantri;
import Validasi.ValidasiInputan;
import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PanelDataWaliSantri extends javax.swing.JPanel {

    ValidasiInputan vld = new ValidasiInputan();
    CrudWaliSantri crudws = new CrudWaliSantri();
    WaliSantri ws = new WaliSantri();

    public PanelDataWaliSantri() {
        initComponents();
        tableWaliSantri();

        buttonEdit.setEnabled(false);
        buttonHapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        teksNamaAyah = new javax.swing.JTextField();
        validasiTeksNamaAyah = new javax.swing.JLabel();
        cekValidasiNamaAyah = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableWaliSantri = new javax.swing.JTable();
        teksNamaIbu = new javax.swing.JTextField();
        validasiTeksNamaIbu = new javax.swing.JLabel();
        cekValidasiNamaIbu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        teksNoHp = new javax.swing.JTextField();
        cekValidasiNoHp = new javax.swing.JLabel();
        validasiTeksNoHp = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        teksSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JLabel();
        buttonFilter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        teksID = new javax.swing.JTextField();
        buttonReset = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(910, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ayah");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        teksNamaAyah.setBackground(new java.awt.Color(255, 255, 255));
        teksNamaAyah.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNamaAyah.setForeground(new java.awt.Color(0, 0, 0));
        teksNamaAyah.setText("Masukan Nama...");
        teksNamaAyah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNamaAyahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNamaAyahFocusLost(evt);
            }
        });
        teksNamaAyah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNamaAyahKeyReleased(evt);
            }
        });
        jPanel1.add(teksNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 450, 30));

        validasiTeksNamaAyah.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNamaAyah.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 300, 10));

        cekValidasiNamaAyah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNamaAyah, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 30));

        tableWaliSantri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableWaliSantri.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableWaliSantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableWaliSantriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableWaliSantri);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 910, 360));

        teksNamaIbu.setBackground(new java.awt.Color(255, 255, 255));
        teksNamaIbu.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNamaIbu.setForeground(new java.awt.Color(0, 0, 0));
        teksNamaIbu.setText("Masukan Nama...");
        teksNamaIbu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNamaIbuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNamaIbuFocusLost(evt);
            }
        });
        teksNamaIbu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNamaIbuKeyReleased(evt);
            }
        });
        jPanel1.add(teksNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 450, 30));

        validasiTeksNamaIbu.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNamaIbu.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 300, 10));

        cekValidasiNamaIbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNamaIbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 30));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ibu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        buttonTambah.setBackground(new java.awt.Color(51, 255, 0));
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add (1).png"))); // NOI18N
        buttonTambah.setText("TAMBAH");
        buttonTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonTambahMouseExited(evt);
            }
        });
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 40));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("No. HP");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        teksNoHp.setBackground(new java.awt.Color(255, 255, 255));
        teksNoHp.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksNoHp.setForeground(new java.awt.Color(0, 0, 0));
        teksNoHp.setText("Masukan No.HP...");
        teksNoHp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksNoHpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksNoHpFocusLost(evt);
            }
        });
        teksNoHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teksNoHpKeyReleased(evt);
            }
        });
        jPanel1.add(teksNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 450, 30));

        cekValidasiNoHp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/true (1).png"))); // NOI18N
        jPanel1.add(cekValidasiNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, 30));

        validasiTeksNoHp.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        validasiTeksNoHp.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(validasiTeksNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 300, 10));

        buttonEdit.setBackground(new java.awt.Color(0, 255, 204));
        buttonEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit (1).png"))); // NOI18N
        buttonEdit.setText("EDIT");
        buttonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEditMouseExited(evt);
            }
        });
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 40));

        buttonHapus.setBackground(new java.awt.Color(255, 0, 0));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete (1).png"))); // NOI18N
        buttonHapus.setText("HAPUS");
        buttonHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHapusMouseExited(evt);
            }
        });
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 40));

        teksSearch.setBackground(new java.awt.Color(255, 255, 255));
        teksSearch.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksSearch.setForeground(new java.awt.Color(0, 0, 0));
        teksSearch.setText("Search...");
        teksSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teksSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teksSearchFocusLost(evt);
            }
        });
        jPanel1.add(teksSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 260, 30));

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search (1).png"))); // NOI18N
        buttonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchMouseClicked(evt);
            }
        });
        jPanel1.add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, -1, 50));

        buttonFilter.setBackground(new java.awt.Color(153, 153, 153));
        buttonFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonFilter.setForeground(new java.awt.Color(255, 255, 255));
        buttonFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FILTER (1).png"))); // NOI18N
        buttonFilter.setText("FILTER");
        buttonFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonFilterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonFilterMouseExited(evt);
            }
        });
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, 40));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        teksID.setBackground(new java.awt.Color(255, 255, 255));
        teksID.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        teksID.setForeground(new java.awt.Color(0, 0, 0));
        teksID.setText("AUTO INCREMENT");
        teksID.setEnabled(false);
        jPanel1.add(teksID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 450, 30));

        buttonReset.setBackground(new java.awt.Color(102, 102, 102));
        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reset (1).png"))); // NOI18N
        buttonReset.setText("RESET");
        buttonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonResetMouseExited(evt);
            }
        });
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });
        jPanel1.add(buttonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void tableWaliSantri() {
        tableWaliSantri.setModel(crudws.tampilWaliSantri());
    }

    private void teksNamaAyahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaAyahFocusGained
        if (teksNamaAyah.getText().equals("Masukan Nama...")) {
            teksNamaAyah.setText("");
        }
    }//GEN-LAST:event_teksNamaAyahFocusGained

    private void teksNamaAyahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaAyahFocusLost
        if (teksNamaAyah.getText().equals("")) {
            teksNamaAyah.setText("Masukan Nama...");
            validasiTeksNamaAyah.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaAyahFocusLost

    private void teksNamaAyahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNamaAyahKeyReleased
        if (!teksNamaAyah.getText().contains(" ")) {
            validasiTeksNamaAyah.setText("Nama Minimal Terdiri Dari 2 Kata");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        } else if (teksNamaAyah.getText().length() > 60) {
            validasiTeksNamaAyah.setText("Maksimal 60 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        } else if (teksNamaAyah.getText().length() < 10) {
            validasiTeksNamaAyah.setText("Minimal 10 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        } else {
            validasiTeksNamaAyah.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        }

        if (vld.cekNama(teksNamaAyah.getText()) != 0) {
            validasiTeksNamaAyah.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaAyah.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaAyahKeyReleased

    private void teksNamaIbuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaIbuFocusGained
        if (teksNamaIbu.getText().equals("Masukan Nama...")) {
            teksNamaIbu.setText("");
        }
    }//GEN-LAST:event_teksNamaIbuFocusGained

    private void teksNamaIbuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNamaIbuFocusLost
        if (teksNamaIbu.getText().equals("")) {
            teksNamaIbu.setText("Masukan Nama...");
            validasiTeksNamaIbu.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaIbuFocusLost

    private void teksNamaIbuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNamaIbuKeyReleased
        if (!teksNamaIbu.getText().contains(" ")) {
            validasiTeksNamaIbu.setText("Nama Minimal Terdiri Dari 2 Kata");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        } else if (teksNamaIbu.getText().length() > 60) {
            validasiTeksNamaIbu.setText("Maksimal 60 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        } else if (teksNamaIbu.getText().length() < 10) {
            validasiTeksNamaIbu.setText("Minimal 10 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        } else {
            validasiTeksNamaIbu.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        }

        if (vld.cekNama(teksNamaIbu.getText()) != 0) {
            validasiTeksNamaIbu.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNamaIbu.setIcon(icon);
        }
    }//GEN-LAST:event_teksNamaIbuKeyReleased

    private void buttonTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahMouseEntered
        buttonTambah.setForeground(Color.BLACK);
    }//GEN-LAST:event_buttonTambahMouseEntered

    private void buttonTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTambahMouseExited
        buttonTambah.setForeground(Color.white);
    }//GEN-LAST:event_buttonTambahMouseExited

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Menambahkan Data Wali Santri?",
                "Tambah Wali Santri",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksNamaAyah.getText().equals("Masukan Nama...") || teksNamaIbu.getText().equals("Masukan Nama...") || teksNoHp.getText().equals("Masukan No.HP...")) {
                JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar", "", JOptionPane.WARNING_MESSAGE);
            } else {

                ws.setAyah(teksNamaAyah.getText().toUpperCase());
                ws.setIbu(teksNamaIbu.getText().toUpperCase());
                ws.setNoHp(teksNoHp.getText());

                if (crudws.validasiWaliSantri(ws) == 0) {
                    if (crudws.tambahWaliSantri(ws) == 1 && vld.cekNama(teksNamaAyah.getText()) == 0 && vld.cekNama(teksNamaIbu.getText()) == 0 && vld.cekNoHp(teksNoHp.getText()) == 0) {
                        JOptionPane.showMessageDialog(this, "Data Wali Santri Berhasil Ditambahkan", "", JOptionPane.INFORMATION_MESSAGE);
                        tableWaliSantri();
                    } else {
                        JOptionPane.showMessageDialog(this, "Data Wali Santri Gagal Ditambahkan", "", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Nama Sudah Terdaftar", "", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void teksNoHpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNoHpFocusGained
        if (teksNoHp.getText().equals("Masukan No.HP...")) {
            teksNoHp.setText("");
        }
    }//GEN-LAST:event_teksNoHpFocusGained

    private void teksNoHpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksNoHpFocusLost
        if (teksNoHp.getText().isEmpty()) {
            teksNoHp.setText("Masukan No.HP...");
            validasiTeksNoHp.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNoHp.setIcon(icon);
        }
    }//GEN-LAST:event_teksNoHpFocusLost

    private void teksNoHpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teksNoHpKeyReleased
        if (teksNoHp.getText().length() < 11) {
            validasiTeksNoHp.setText("Minimal 11 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNoHp.setIcon(icon);
        } else if (teksNoHp.getText().length() > 13) {
            validasiTeksNoHp.setText("Maksimal 13 Karakter");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNoHp.setIcon(icon);
        } else {
            validasiTeksNoHp.setText("");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/true (1).png");
            cekValidasiNoHp.setIcon(icon);
        }

        if (vld.cekNoHp(teksNoHp.getText()) != 0) {
            validasiTeksNoHp.setText("Masukan Data Dengan Benar");
            ImageIcon icon = new ImageIcon("C:/Users/user/OneDrive/Documents/Bahasa Fundamental/JAVA/ProjekJava - Ahmad Faisal Hidayat/src/gambar/false (1).png");
            cekValidasiNoHp.setIcon(icon);
        }
    }//GEN-LAST:event_teksNoHpKeyReleased

    private void buttonEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseEntered
        if (buttonEdit.isEnabled()) {
            buttonEdit.setForeground(Color.black);
        }
    }//GEN-LAST:event_buttonEditMouseEntered

    private void buttonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditMouseExited
        if (buttonEdit.isEnabled()) {
            buttonEdit.setForeground(Color.white);
        }
    }//GEN-LAST:event_buttonEditMouseExited

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Mengedit Data Wali Santri?",
                "Edit Santri",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksNamaAyah.getText().equals("Masukan Nama...") || teksNamaIbu.getText().equals("Masukan Nama...") || teksNoHp.getText().equals("Masukan No.HP...")) {
                JOptionPane.showMessageDialog(this, "Masukan Data Dengan Benar", "", JOptionPane.WARNING_MESSAGE);
            } else {
                
                ws.setId(Integer.parseInt(teksID.getText()));
                ws.setAyah(teksNamaAyah.getText().toUpperCase());
                ws.setIbu(teksNamaIbu.getText().toUpperCase());
                ws.setNoHp(teksNoHp.getText());

                if (crudws.editWaliSantri(ws) == 1 && vld.cekNama(teksNamaAyah.getText()) == 0 && vld.cekNama(teksNamaIbu.getText()) == 0 && vld.cekNoHp(teksNoHp.getText()) == 0) {
                    JOptionPane.showMessageDialog(this, "Data Wali Santri Berhasil Diedit", "", JOptionPane.INFORMATION_MESSAGE);
                    tableWaliSantri();
                } else {
                    JOptionPane.showMessageDialog(this, "Data Wali Santri Gagal Diedit", "", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHapusMouseEntered
        if (buttonHapus.isEnabled()) {
            buttonHapus.setForeground(Color.black);
        }
    }//GEN-LAST:event_buttonHapusMouseEntered

    private void buttonHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHapusMouseExited
        if (buttonHapus.isEnabled()) {
            buttonHapus.setForeground(Color.white);
        }
    }//GEN-LAST:event_buttonHapusMouseExited

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda Ingin Menghapus Data Wali Santri?",
                "Hapus Santri",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            if (teksID.getText().equals("AUTO INCREMENT")) {
                System.out.println("ID Tidak Ditemukan");
            } else {
                ws.setId(Integer.parseInt(teksID.getText()));
                if (crudws.hapusWaliSantri(ws) == 1) {
                    tableWaliSantri();
                    JOptionPane.showMessageDialog(this, "Data Wali Santri Berhasil Dihapus", "", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Wali Santri Gagal Dihapus", "", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void teksSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksSearchFocusGained
        if (teksSearch.getText().equals("Search...")) {
            teksSearch.setText("");
        }
    }//GEN-LAST:event_teksSearchFocusGained

    private void teksSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teksSearchFocusLost
        if (teksSearch.getText().isEmpty()) {
            teksSearch.setText("Search...");
        }
    }//GEN-LAST:event_teksSearchFocusLost

    private void buttonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchMouseClicked
        String by = teksSearch.getText();
        tableWaliSantri.setModel(crudws.cariWaliSantri(by));
    }//GEN-LAST:event_buttonSearchMouseClicked

    private void buttonFilterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFilterMouseEntered
        buttonFilter.setForeground(Color.black);
    }//GEN-LAST:event_buttonFilterMouseEntered

    private void buttonFilterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFilterMouseExited
        buttonFilter.setForeground(Color.white);
    }//GEN-LAST:event_buttonFilterMouseExited

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        Component source = (Component) evt.getSource();
        Object urut = JOptionPane.showInputDialog(source,
                "Pilih Salah Satu",
                "Urut Berdasarkan?", JOptionPane.QUESTION_MESSAGE,
                null, new String[]{"ID", "AYAH", "IBU"}, "ID");
        Object order = JOptionPane.showInputDialog(source,
                "Pilih Salah Satu",
                "Order By", JOptionPane.QUESTION_MESSAGE,
                null, new String[]{"ASC", "DESC"}, "ASC");
        tableWaliSantri.setModel(crudws.filterWaliSantri((String) urut, (String) order));
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void tableWaliSantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableWaliSantriMouseClicked
        buttonEdit.setEnabled(true);
        buttonHapus.setEnabled(true);
        buttonTambah.setEnabled(false);

        int baris = tableWaliSantri.getSelectedRow();
        teksID.setText(tableWaliSantri.getModel().getValueAt(baris, 0).toString());
        teksNamaAyah.setText(tableWaliSantri.getModel().getValueAt(baris, 1).toString());
        teksNamaIbu.setText(tableWaliSantri.getModel().getValueAt(baris, 2).toString());
        teksNoHp.setText(tableWaliSantri.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tableWaliSantriMouseClicked

    private void buttonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseEntered
        buttonReset.setForeground(Color.black);
    }//GEN-LAST:event_buttonResetMouseEntered

    private void buttonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseExited
        buttonReset.setForeground(Color.white);
    }//GEN-LAST:event_buttonResetMouseExited

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        buttonTambah.setEnabled(true);
        buttonEdit.setEnabled(false);
        buttonHapus.setEnabled(false);

        teksID.setText("AUTO INCREMENT");
        teksNamaAyah.setText("Masukan Nama...");
        teksNamaIbu.setText("Masukan Nama...");
        teksNoHp.setText("Masukan No.HP...");
        teksSearch.setText("Search...");
        tableWaliSantri();

    }//GEN-LAST:event_buttonResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JLabel buttonSearch;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel cekValidasiNamaAyah;
    private javax.swing.JLabel cekValidasiNamaIbu;
    private javax.swing.JLabel cekValidasiNoHp;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableWaliSantri;
    private javax.swing.JTextField teksID;
    private javax.swing.JTextField teksNamaAyah;
    private javax.swing.JTextField teksNamaIbu;
    private javax.swing.JTextField teksNoHp;
    private javax.swing.JTextField teksSearch;
    private javax.swing.JLabel validasiTeksNamaAyah;
    private javax.swing.JLabel validasiTeksNamaIbu;
    private javax.swing.JLabel validasiTeksNoHp;
    // End of variables declaration//GEN-END:variables
}
